---
Profiles:
  FourOrgsGenesis:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
      - *OrdererOrg
    Consortiums:
      BankConsortium:
        Organizations:
        - *BankOrg
        - *UserOrg
        - *PassportOrg
        - *GovtOrg
  FourOrgsChannel:
    Consortium: BankConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
      - *BankOrg
      - *UserOrg
      - *PassportOrg
      - *GovtOrg

Organizations:
- &OrdererOrg
  Name: OrdererOrg
  ID: OrdererMSP
  MSPDir: cli/peers/ordererOrganizations/orderer-org/msp
- &BankOrg
  Name: BankOrgMSP
  ID: BankOrgMSP
  MSPDir: cli/peers/peerOrganizations/insurance-org/msp
  AnchorPeers:
  - Host: insurance-peer
    Port: 7051
- &UserOrg
  Name: UserOrgMSP
  ID: UserOrgMSP
  MSPDir: cli/peers/peerOrganizations/shop-org/msp
  AnchorPeers:
  - Host: shop-peer
    Port: 7051
- &PassportOrg
  Name: PassportOrgMSP
  ID: PassportOrgMSP
  MSPDir: cli/peers/peerOrganizations/repairshop-org/msp
  AnchorPeers:
  - Host: repairshop-peer
    Port: 7051
- &GovtOrg
    Name: GovtOrgMSP
    ID: GovtOrgMSP
    MSPDir: cli/peers/peerOrganizations/police-org/msp
    AnchorPeers:
    - Host: police-peer
      Port: 7051

Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
  - orderer0:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:

Application: &ApplicationDefaults
  Organizations:
